### ISSUE TITLE
read api and ssh endpoints from .lagoon.yml file

### ISSUE THREAD

**Issue by twardnw** [uselagoon/lagoon-cli#103]
When working on a project that uses other-than default endpoints, it would be good for the CLI to read these from the project's own .lagoon.yml

**Comment by shreddedbacon** [comment]
Possible to do this, but would involve a lot of extra work to make it happen.

Is it possible to utilise the following that is in lagoon-cli v0.8.+ ?
```
export LAGOONCONFIG=/path/to/mycluster.yaml
```
where `/path/to/mycluster.yaml` could be
```
current: mycluster
default: mycluster
lagoons:
  mycluster:
    graphql: https://api.lagoon.amazeeio.cloud/graphql
    hostname: ssh.lagoon.amazeeio.cloud
    kibana: https://logs-db-ui-lagoon-master.ch.amazee.io/
    port: 32222
    ui: https://ui-lagoon-master.ch.amazee.io
```

Having that envvar defined will mean any commands run will execute against the cluster defined in the config that is being given.
